//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIDemonV2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIDemonV2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deepseek-ai/DeepSeek-R1;deepseek-ai/DeepSeek-R1-Distill-Llama-70B;deepseek-ai/DeepSeek-R1-Distill-Qwen-32B;meta-llama/Llama-3.3-70B-Instruct;databricks/dbrx-instruct;Qwen/QwQ-32B-Preview;mistralai/Ministral-8B-Instruct-2410;deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B;deepseek-ai/DeepSeek-R1-Distill-Qwen-7B;deepseek-ai/DeepSeek-R1-Distill-Qwen-14B;deepseek-ai/DeepSeek-R1-Distill-Llama-8B;netease-youdao/Confucius-o1-14B;nvidia/AceMath-7B-Instruct;google/gemma-2-9b-it;neuralmagic/Llama-3.1-Nemotron-70B-Instruct- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AIModels {
            get {
                return ResourceManager.GetString("AIModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to python;powershell.
        /// </summary>
        internal static string ProgrammingLanguages {
            get {
                return ResourceManager.GetString("ProgrammingLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P@ssword1.
        /// </summary>
        internal static string SQLiteDBPass {
            get {
                return ResourceManager.GetString("SQLiteDBPass", resourceCulture);
            }
        }
    }
}
