name: Build and Create Installer

on:
  push:
    branches:
      - instalator

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install Inno Setup
      run: choco install innosetup --no-progress -y

    - name: Publish Application (Windows)
      run: |
        dotnet publish AIDemon2/AIDemon2.csproj `
        -c Release `
        --self-contained true `
        -r win-x64 `
        -o AIDemon2/bin/Release/publish-win

    - name: Build Inno Setup Installer
      run: |
        "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" Installer.iss
      shell: cmd

    - name: Publish Application (Linux)
      run: |
        dotnet publish AIDemon2/AIDemon2.csproj `
        -c Release `
        --self-contained true `
        -r linux-x64 `
        -o AIDemon2/bin/Release/publish-linux

    - name: Create tar.gz for Linux
      run: |
        Compress-Archive -Path AIDemon2/bin/Release/publish-linux/* -DestinationPath AIDemon2_Linux.zip

    - name: Upload Windows Installer
      uses: actions/upload-artifact@v4
      with:
        name: AIDemon2-Installer
        path: ${{ github.workspace }}/Output/AIDemon2_Installer.exe

    - name: Upload Linux Build
      uses: actions/upload-artifact@v4
      with:
        name: AIDemon2-Linux
        path: ${{ github.workspace }}/Output/AIDemon2_Linux.zip

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Release v1.0.${{ github.run_number }}
        draft: false
        prerelease: false
        files: |
          ${{ github.workspace }}/Output/AIDemon2_Installer.exe
          ${{ github.workspace }}/Output/AIDemon2_Linux.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
