name: Build and Create Installer

on:
  push:
    branches:
      - instalator

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write  # Uprawnienia do tworzenia release

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install Inno Setup
      run: choco install innosetup --no-progress -y

    - name: Publish Application (self-contained)
      run: |
        dotnet publish AIDemon2/AIDemon2.csproj `
        -c Release `
        --self-contained true `
        -o bin\publish


    - name: Build Inno Setup Installer
      run: |
        "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" Installer.iss

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: AIDemon2-Installer
        path: "*.exe"

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Release v1.0.${{ github.run_number }}
        draft: false
        prerelease: false
        files: "*.exe"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
