name: Build and Publish ClickOnce .NET 8 App

on:
  push:
    branches:
      - instalator

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Publish Application
      run: |
        dotnet publish AIDemon2/AIDemon2.csproj -c Release -r win-x86 --self-contained true `
          /p:PublishSingleFile=true `
          /p:PublishReadyToRun=true `
          /p:ApplicationVersion=1.0.${{ github.run_number }} `
          -o ./publish
          
    - name: Zip Publish Directory
      run: Compress-Archive -Path ./publish/* -DestinationPath ClickOnce_${{ github.ref_name }}.zip

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: clickonce-app
        path: |
          ./publish/*.exe
          ClickOnce_${{ github.ref_name }}.zip

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Create Tag
      env:
        GITHUB_PAT: ${{ secrets.PAT_TOKEN }}
      run: |
        git tag v1.0.${{ github.run_number }}
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git v1.0.${{ github.run_number }}

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.${{ github.run_number }}
        files: |
          ./publish/*.exe
          ClickOnce_${{ github.run_number }}.zip
